package com.github.andreluizdev12.logiflow.shared.exceptions;

public enum ErrorCode {

    CLIENT_NOT_FOUND,
    CLIENT_ALREADY_EXISTS,
    INVALID_DOCUMENT,
    VALIDATION_ERROR,
    BUSINESS_RULE_VIOLATION,
    INTERNAL_SERVER_ERROR,
    INVALID_DOCUMENT_FOR_PERSON_TYPE,
    INVALID_EMAIL,
    INVALID_PHONE,
    INVALID_CLIENT_DATA

}